agents:
  agent:
    replay_buffer_size: 1000000
  mbrl_agent:
    train_batch_size: 2500
    train_interaction_steps: 250
    eval_interaction_steps: 100
    episode_length: 1000
    warmup_timesteps: 250
    policy: cem_mpc
    model: mlp_ensemble
