agents:
  agent:
    replay_buffer_size: 1000000
  mbrl_agent:
    train_batch_size: 1000000
    train_interaction_steps: 300
    episode_length: 150
    warmup_timesteps: 1000
    policy: cem_mpc
    model: mlp_ensemble
    scale_features: False
