options:
  trainer_options:
    video_log_frequency: 3
    log_frequency: 1
    max_video_length: 40
    eval_interaction_steps: 20
    eval_episode_length: 20
    training_logger_params:
      fps: 15
  seed: 1
  training_iterations: 5
  agent: mbrl_agent
  environment: MbrlInvertedPendulum-v2


