options:
  video_log_frequency: 0
  seed: null
  agent: mbrl_agent
  environment: cartpole

models:
    ensembled_anchored_nn:
      anchored_nn:
        learning_rate: 8
        anchor: True
        yarden: True

