models:
  mlp_ensemble:
    ensemble_size: 5
    n_epochs: 250
    batch_size: 64
    validation_split: 0.1
    learning_rate: 0.0001
    mlp_params:
      n_layers: 3
      units: 64
      activation: tf.nn.relu
      dropout_rate: 0.0