models:
  anchored_mlp_ensemble:
    ensemble_size: 5
    n_epochs: 250
    batch_size: 64
    mlp_params:
      learning_rate: 0.0001
      n_layers: 3
      hidden_size: 64
      activation: tf.nn.relu
      anchor: False
      init_std_bias: 0.0
      init_std_weights: 0.0
      data_noise: 0.0
  mlp_ensemble:
    ensemble_size: 5
    n_epochs: 250
    batch_size: 64
    validation_split: 0.1
    mlp_params:
      learning_rate: 0.0001
      n_layers: 3
      units: 64
      activation: tf.nn.relu
      dropout_rate: 0.0