models:
  mlp_ensemble:
    ensemble_size: 5
    n_epochs: 60
    batch_size: 100
    validation_split: 0.1
    learning_rate: 0.001
    mlp_params:
      n_layers: 2
      units: 100
      activation: tf.nn.relu
      dropout_rate: 0.0